using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace MonsterSupergroup.GAS.Editor
{
    public static class ModifierRegistryGenerator
    {
        public const string OutputPath = "Assets/_Project/GAS/Core/Generated/GeneratedModifierRegistry.g.cs";

        [MenuItem("Tools/MonsterSupergroup/GAS/Rebuild Registry")]
        public static void Rebuild()
        {
            string source = GenerateSource();
            string directory = Path.GetDirectoryName(OutputPath);
            if (!string.IsNullOrEmpty(directory))
            {
                Directory.CreateDirectory(directory);
            }

            File.WriteAllText(OutputPath, source, new UTF8Encoding(false));
            AssetDatabase.ImportAsset(OutputPath, ImportAssetOptions.ForceUpdate);
            Debug.Log($"Generated GAS modifier registry at {OutputPath}.");
        }

        public static bool IsCurrent()
        {
            if (!File.Exists(OutputPath))
            {
                return false;
            }

            string actual = NormalizeNewlines(File.ReadAllText(OutputPath));
            return string.Equals(actual, NormalizeNewlines(GenerateSource()), StringComparison.Ordinal);
        }

        public static string GenerateSource()
        {
            IReadOnlyList<ModifierDescriptor> equipment = ModifierTypeCatalog.Equipment;
            IReadOnlyList<ModifierDescriptor> perks = ModifierTypeCatalog.Perks;
            EnsureUniqueIds(equipment, "equipment");
            EnsureUniqueIds(perks, "perk");

            var source = new StringBuilder();
            source.AppendLine("// <auto-generated />");
            source.AppendLine("namespace MonsterSupergroup.GAS");
            source.AppendLine("{");
            source.AppendLine("    public static class GeneratedModifierRegistry");
            source.AppendLine("    {");
            source.AppendLine("        public static ModifierRegistry Create()");
            source.AppendLine("        {");
            source.AppendLine("            var builder = new ModifierRegistry.Builder();");

            foreach (ModifierDescriptor descriptor in equipment)
            {
                source.Append("            builder.RegisterEquipment<global::");
                source.Append(GetCSharpTypeName(descriptor.ModifierType));
                source.Append(", global::");
                source.Append(GetCSharpTypeName(descriptor.ParametersType));
                source.AppendLine(">(");
                source.Append("                new EquipmentModifierID(0x");
                source.Append(descriptor.Id.ToString("X8"));
                source.AppendLine("u),");
                source.Append("                parameters => new global::");
                source.Append(GetCSharpTypeName(descriptor.ModifierType));
                source.AppendLine("(parameters));");
            }

            foreach (ModifierDescriptor descriptor in perks)
            {
                source.Append("            builder.RegisterPerk<global::");
                source.Append(GetCSharpTypeName(descriptor.ModifierType));
                source.Append(", global::");
                source.Append(GetCSharpTypeName(descriptor.ParametersType));
                source.AppendLine(">(");
                source.Append("                new PerkModifierID(0x");
                source.Append(descriptor.Id.ToString("X8"));
                source.AppendLine("u),");
                source.Append("                parameters => new global::");
                source.Append(GetCSharpTypeName(descriptor.ModifierType));
                source.AppendLine("(parameters));");
            }

            source.AppendLine("            return builder.Build();");
            source.AppendLine("        }");
            source.AppendLine("    }");
            source.AppendLine("}");
            return source.ToString();
        }

        private static void EnsureUniqueIds(IReadOnlyList<ModifierDescriptor> descriptors, string domain)
        {
            uint[] duplicates = descriptors
                .GroupBy(descriptor => descriptor.Id)
                .Where(group => group.Count() > 1)
                .Select(group => group.Key)
                .ToArray();
            if (duplicates.Length > 0)
            {
                throw new InvalidOperationException(
                    $"Duplicate {domain} modifier IDs: {string.Join(", ", duplicates.Select(id => id.ToString()))}.");
            }
        }

        private static string GetCSharpTypeName(Type type)
        {
            return type.FullName?.Replace('+', '.')
                ?? throw new InvalidOperationException($"Type {type} has no full name.");
        }

        private static string NormalizeNewlines(string value)
        {
            return value.Replace("\r\n", "\n").Replace('\r', '\n');
        }
    }
}
